#!/bin/bash
set -e
set -u

function dump_denoms() {
    ./utils/update-manifest
}

function generate_for_user() {
    a_username="${1}"
    for _ in $(seq 1 10); do
        ./bin/dash-cli-wallet "${a_username}" generatetoaddress 10 "$(cat ./data/w-"${a_username}"-address-0)"
    done
    ./bin/dash-cli-listtransactions "${a_username}" 500 > ./data/w-"${a_username}"-txns.json
}

function init_user() {
    a_username="${1}"
    ./bin/wallet-create "${a_username}"
    ./bin/dash-cli-wallet "${a_username}" getnewaddress > ./data/w-"${a_username}"-address-0
    ./bin/dash-cli-wallet "${a_username}" getrawchangeaddress > ./data/w-"${a_username}"-change-address-0
    ./bin/dash-cli-wallet "${a_username}" walletpassphrase foobar 100000000
    ./bin/dash-cli-wallet "${a_username}" dumpprivkey "$(cat ./data/w-"${a_username}"-address-0)" > ./data/w-"${a_username}"-privkey-0
    for _ in $(seq 1 4); do
        ./bin/dash-cli-wallet "${a_username}" generatetoaddress 10 "$(cat ./data/w-"${a_username}"-address-0)"
    done
    ./bin/dash-cli-listtransactions "${a_username}" 500 > ./data/w-"${a_username}"-txns.json
}

HELP=0
CREATE=0
UNLOCK=0
TXN=0
UNUSED=0
DUMP_DENOMS=0
HAN=0
CHEWIE=0
LUKE=0
FOOBAR=0
PSEND=0
LOAD_HAN=0
LOAD_CHEWIE=0
LOAD_LUKE=0
LOAD_FOOBAR=0
LOAD_PSEND=0

if test -z "${*}"; then
    set -- "--help"
fi
for arg in "${@}"; do
    if [[ $arg == "--all" ]]; then
        CREATE=1
        UNLOCK=1
        TXN=1
        UNUSED=1
        DUMP_DENOMS=1
        HAN=1
        CHEWIE=1
        LUKE=1
        FOOBAR=1
        PSEND=1
        LOAD_HAN=1
        LOAD_CHEWIE=1
        LOAD_LUKE=1
        LOAD_FOOBAR=1
        LOAD_PSEND=1
        break
    fi

    if [[ $arg == "--help" || $arg == "-h" ]]; then
        HELP=1
    fi
    if [[ $arg == "--create" ]]; then
        CREATE=1
    fi
    if [[ $arg == "--dump-denoms" ]]; then
        DUMP_DENOMS=1
    fi
    if [[ $arg == "--txn" ]]; then
        TXN=1
    fi
    if [[ $arg == "--create" ]]; then
        CREATE=1
    fi
    if [[ $arg == "--unlock" ]]; then
        UNLOCK=1
    fi
    if [[ $arg == "--han" ]]; then
        HAN=1
    fi
    if [[ $arg == "--luke" ]]; then
        LUKE=1
    fi
    if [[ $arg == "--chewie" ]]; then
        CHEWIE=1
    fi
    if [[ $arg == "--psend" ]]; then
        PSEND=1
    fi

    if [[ $arg == "--load-han" ]]; then
        LOAD_HAN=1
    fi

    if [[ $arg == "--load-chewie" ]]; then
        LOAD_CHEWIE=1
    fi
    if [[ $arg == "--load-luke" ]]; then
        LOAD_LUKE=1
    fi
    if [[ $arg == "--load-psend" ]]; then
        LOAD_PSEND=1
    fi
    if [[ $arg == "--load-foobar" ]]; then
        LOAD_FOOBAR=1
    fi

done

if [[ $HELP == 1 ]]; then
    echo "Usage: $0 [--all|--dump-denoms|--create|--unlock|--txn|--unused]"
    echo "  --all           Same as passing the following flags: "
    echo "                  --dump-denoms --create --unlock --txn --unused "
    echo "                  --han --chewie --luke --psend --foobar"
    echo "  --dump-denoms   runs the script at ./utils/update-manifest"
    echo "  --txn           generates transactions to all wallets listed"
    echo "  --create        creates all wallets, private,keys, and coins. Overwriting previous configs."
    echo "  --unlock        Unlocks all the wallets using walletpassphrase"

    echo "  --foobar        Create Foobar's wallet"
    echo "  --psend         Create Psend's wallet"
    echo "  --luke          Create Luke's wallet"
    echo "  --han           Create Han's wallet"
    echo "  --chewie        Create Chewie's wallet"
    echo
    echo "  --load-foobar   Generate 100 blocks to Foobar's wallet"
    echo "  --load-psend    Generate 100 blocks to Psend's wallet"
    echo "  --load-luke     Generate 100 blocks to Luke's wallet"
    echo "  --load-han      Generate 100 blocks to Han's wallet"
    echo "  --load-chewie   Generate 100 blocks to Chewie's wallet"
    echo
    echo "  --help|-h       This help screen"
    echo
    exit 1
fi

if [[ $CREATE == 1 ]]; then
    ./bin/wallet-create 'foobar'
    ./bin/wallet-create 'psend'
    ./bin/wallet-create 'han'
    ./bin/wallet-create 'luke'
    ./bin/wallet-create 'chewie'

    ./bin/dash-cli-wallet 'foobar' getnewaddress > ./data/w-foobar-address-0
    ./bin/dash-cli-wallet 'psend' getnewaddress > ./data/w-psend-address-0
    ./bin/dash-cli-wallet 'luke' getnewaddress > ./data/w-luke-address-0
    ./bin/dash-cli-wallet 'han' getnewaddress > ./data/w-han-address-0
    ./bin/dash-cli-wallet 'chewie' getnewaddress > ./data/w-chewie-address-0

    ./bin/dash-cli-wallet 'foobar' getnewaddress > ./data/w-foobar-change-address-0
    ./bin/dash-cli-wallet 'psend' getnewaddress > ./data/w-psend-change-address-0
    ./bin/dash-cli-wallet 'luke' getnewaddress > ./data/w-luke-change-address-0
    ./bin/dash-cli-wallet 'han' getnewaddress > ./data/w-han-change-address-0
    ./bin/dash-cli-wallet 'chewie' getnewaddress > ./data/w-chewie-change-address-0
fi

if [[ $UNLOCK == 1 ]]; then
    b_wallet_salt='foobar'
    b_unlock_time=100000000

    ./bin/dash-cli-wallet 'foobar' walletpassphrase "${b_wallet_salt}" "${b_unlock_time}"
    ./bin/dash-cli-wallet 'psend' walletpassphrase "${b_wallet_salt}" "${b_unlock_time}"
    ./bin/dash-cli-wallet 'luke' walletpassphrase "${b_wallet_salt}" "${b_unlock_time}"
    ./bin/dash-cli-wallet 'han' walletpassphrase "${b_wallet_salt}" "${b_unlock_time}"
    ./bin/dash-cli-wallet 'chewie' walletpassphrase "${b_wallet_salt}" "${b_unlock_time}"

    ./bin/dash-cli-wallet 'foobar' dumpprivkey "$(cat ./data/w-foobar-address-0)" \
        > ./data/w-foobar-privkey-0
    ./bin/dash-cli-wallet 'psend' dumpprivkey "$(cat ./data/w-psend-address-0)" \
        > ./data/w-psend-privkey-0
    ./bin/dash-cli-wallet 'luke' dumpprivkey "$(cat ./data/w-luke-address-0)" \
        > ./data/w-luke-privkey-0
    ./bin/dash-cli-wallet 'han' dumpprivkey "$(cat ./data/w-han-address-0)" \
        > ./data/w-han-privkey-0
    ./bin/dash-cli-wallet 'chewie' dumpprivkey "$(cat ./data/w-chewie-address-0)" \
        > ./data/w-chewie-privkey-0
fi

if [[ $TXN == 1 ]]; then
    for _ in $(seq 1 10); do
        ./bin/dash-cli-wallet 'foobar' generatetoaddress 10 "$(cat ./data/w-foobar-address-0)"
        ./bin/dash-cli-wallet 'psend' generatetoaddress 10 "$(cat ./data/w-psend-address-0)"
        ./bin/dash-cli-wallet 'luke' generatetoaddress 10 "$(cat ./data/w-luke-address-0)"
        ./bin/dash-cli-wallet 'han' generatetoaddress 10 "$(cat ./data/w-han-address-0)"
        ./bin/dash-cli-wallet 'chewie' generatetoaddress 10 "$(cat ./data/w-chewie-address-0)"
    done
fi

if [[ $UNUSED == 1 ]]; then
    ./bin/dash-cli-listtransactions 'foobar' 500 > ./data/w-foobar-txns.json
    ./bin/dash-cli-listtransactions 'psend' 500 > ./data/w-psend-txns.json
    ./bin/dash-cli-listtransactions 'luke' 500 > ./data/w-luke-txns.json
    ./bin/dash-cli-listtransactions 'han' 500 > ./data/w-han-txns.json
    ./bin/dash-cli-listtransactions 'chewie' 500 > ./data/w-chewie-txns.json
fi

if [[ $DUMP_DENOMS == 1 ]]; then
    dump_denoms
fi

if [[ $FOOBAR == 1 ]]; then
    init_user 'foobar'
fi
if [[ $PSEND == 1 ]]; then
    init_user 'psend'
fi
if [[ $HAN == 1 ]]; then
    init_user 'han'
fi
if [[ $LUKE == 1 ]]; then
    init_user 'luke'
fi
if [[ $CHEWIE == 1 ]]; then
    init_user 'chewie'
fi

if [[ $LOAD_FOOBAR == 1 ]]; then
    generate_for_user 'foobar'
fi
if [[ $LOAD_PSEND == 1 ]]; then
    generate_for_user 'psend'
fi
if [[ $LOAD_LUKE == 1 ]]; then
    generate_for_user 'luke'
fi
if [[ $LOAD_HAN == 1 ]]; then
    generate_for_user 'han'
fi
if [[ $LOAD_CHEWIE == 1 ]]; then
    generate_for_user 'chewie'
fi
